name: Desplegar a InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Desplegar Web a InfinityFree
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener el código más reciente
      uses: actions/checkout@v4

    - name: 📂 Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/whatsapp-bot/**
          **/scratch/**
          **/*.zip
          **/.env*
          **/admin/uploads/**
          README.md
